# Monitoring and maintenance configuration for the Crypto Trading Bot Web Application

# Logging configuration
[logging]
level = "INFO"
file = "logs/crypto_trading_bot.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Health check configuration
[health_check]
enabled = true
interval = 300  # seconds
endpoints = [
    "/health",
    "/api/health"
]

# Error tracking configuration
[error_tracking]
enabled = true
notification_email = "alerts@example.com"
log_errors = true

# Performance monitoring
[performance]
track_memory_usage = true
track_response_time = true
track_database_queries = true

# Backup configuration
[backup]
enabled = true
interval = 86400  # daily in seconds
retention_days = 7
backup_database = true
backup_user_data = true
