credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$5nU0DVx4/dBwJUqT7rYGTOYRvW9r.GNpOSbHvHQeWFJiXVN7b6ige  # hashed 'admin'
cookie:
  expiry_days: 30
  key: crypto_trading_bot_auth
  name: crypto_trading_bot_auth
